# Generated by Django 3.2.7 on 2021-09-09 11:26

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정된 일시')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='삭제된 일시')),
                ('cover_name', models.TextField(blank=True, null=True, verbose_name='Cover name')),
                ('name', models.TextField(blank=True, null=True, verbose_name='이름')),
                ('email', models.TextField(blank=True, null=True, verbose_name='이메일')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedSecondaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_profile.publicprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile_taggedsecondarytag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedPrimaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_profile.publicprofile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile_taggedprimarytag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='primary_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='primary_tags', through='public_profile.TaggedPrimaryTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='publicprofile',
            name='secondary_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='secondary_tags', through='public_profile.TaggedSecondaryTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
